import { act } from 'react';
import { createRoot } from 'react-dom/client';
import { parseHTML } from 'linkedom';
import { afterEach, expect, it, vi } from 'vitest';
import { SearchStatus } from '../src/components/SearchStatus';

afterEach(() => { vi.useRealTimers(); vi.unstubAllGlobals(); });
it('retains separate live regions and throttles progress announcements to two seconds', () => {
  vi.useFakeTimers();
  const { window, document } = parseHTML('<html><body><div id="root"></div></body></html>');
  vi.stubGlobal('window', window); vi.stubGlobal('document', document); vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT', true);
  const container = document.getElementById('root')!;
  const root = createRoot(container);
  const props = { searching: true, error: '', canResume: false, onResume() {} };
  const progress = (visited: number) => ({ depth: 2, visited, frontierA: 1, frontierB: 1 });
  const render = (visited: number) => act(() => root.render(<SearchStatus {...props} progress={progress(visited)} />));
  act(() => root.render(<SearchStatus {...props} searching={false} />));
  const idleStatus = container.querySelector('[role=status]')!;
  const idleAlert = container.querySelector('[role=alert]')!;
  expect(container.querySelector('[hidden]')).toBeNull();
  expect(idleStatus.textContent).toBe(''); expect(idleAlert.textContent).toBe('');
  render(1);
  const status = container.querySelector('[role=status]')!;
  const alert = container.querySelector('[role=alert]')!;
  expect(status).toBe(idleStatus); expect(alert).toBe(idleAlert);
  expect(container.querySelector('[hidden]')).toBeNull();
  expect(status.textContent).not.toContain('Обнаружено статей: 1');
  act(() => vi.advanceTimersByTime(1000)); render(500);
  expect(status.textContent).not.toContain('500');
  act(() => vi.advanceTimersByTime(1000));
  expect(status.textContent).toContain('Обнаружено статей: 500');
  render(900); act(() => vi.advanceTimersByTime(1999));
  expect(status.textContent).not.toContain('900');
  act(() => root.render(<SearchStatus {...props} searching={false} error="Сеть недоступна" />));
  expect(container.querySelector('[role=status]')).toBe(status);
  expect(container.querySelector('[role=alert]')).toBe(alert);
  expect(alert.textContent).toContain('Сеть недоступна');
  expect(container.querySelector('[hidden]')).toBeNull();
  expect(status.textContent).toBe('');
  act(() => root.render(<SearchStatus {...props} searching={false} notFound={{ limitsHit: 'no_path', visited: 900, depth: 2 }} />));
  expect(container.querySelector('[role=status]')).toBe(status);
  expect(container.querySelector('[role=alert]')).toBe(alert);
  expect(status.textContent).toContain('Путь не найден'); expect(alert.textContent).toBe('');
  expect(container.querySelector('[hidden]')).toBeNull();
  act(() => root.render(<SearchStatus {...props} searching={false} />));
  expect(status.textContent).toBe(''); expect(alert.textContent).toBe('');
  expect(container.querySelector('[hidden]')).toBeNull();
  expect(container.querySelector('.is-empty')).not.toBeNull();
  act(() => root.unmount());
  expect(vi.getTimerCount()).toBe(0);
});
